// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HizliFaturalama.Models;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string TaxNumber { get; set; }

    public string Title { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string UserId { get; set; }

    public DateTime RecordDate { get; set; }

    public string PhoneNumber { get; set; }

    public bool IsActive { get; set; }

    public string UserName { get; set; }
}