// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HizliFaturalama.Models;

public partial class Invoice
{
    public string InvoiceId { get; set; }

    public string CustomerId { get; set; }

    public string InvoiceNumber { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal TotalAmount { get; set; }

    public string UserId { get; set; }

    public DateTime RecordDate { get; set; }
}