// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HizliFaturalama.Models;

public partial class InvoiceLine
{
    public string InvoiceLineId { get; set; }

    public string InvoiceId { get; set; }

    public string ItemId { get; set; }

    public string ItemName { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public string UserId { get; set; }

    public DateTime RecordDate { get; set; }

    public string Unit { get; set; }
}