// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HizliFaturalama.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public DateTime RecordDate { get; set; }

    public string Role { get; set; }
}